obj-y += page_alloc.o slab.o slub.o
obj-y += memblock.o

obj-$(CONFIG_SWAP) += swap.o
obj-$(CONFIG_NUMA) += numa.o
obj-$(CONFIG_COMPACTION) += compaction.o
obj-$(CONFIG_MIGRATION) += migrate.o
obj-$(CONFIG_KSM) += ksm.o
obj-$(CONFIG_TRANSPARENT_HUGEPAGE) += huge_memory.o

obj-$(CONFIG_PERCPU_STATS) += percpu.o
